language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_d472159ded8f_key -iv $encrypted_d472159ded8f_iv
  -in .travis/keyrings/deploy_key.pem.enc -out .travis/keyrings/deploy_key.pem -d
- echo "MAVEN_OPTS='-Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1'" > ~/.mavenrc
- export GOPATH=$HOME/gopath
- eval "$(GIMME_GO_VERSION=1.6 gimme)"
- export PATH=$PATH:$GOPATH/bin
install:
- sudo apt-get -qq update
- go get github.com/nats-io/gnatsd
- sudo apt-get install -y gnupg
script:
- mvn --settings .travis/settings.xml clean verify
after_success:
- mvn --settings .travis/settings.xml coveralls:report
cache:
  directories:
  - "$HOME/.m2"
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/jnats
    branch: master
    jdk: oraclejdk8
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/jnats
    tags: true
    jdk: oraclejdk8
notifications:
  email:
  - larry@apcera.com
env:
  global:
  - GPG_DIR=${TRAVIS_BUILD_DIR}/.travis/keyrings
  - secure: F1pNsvz6aUIO7SoZX8aBP7RczzWO+IDUL7CafEEUkwFmfVcESr+sDauDW+sCW5otwOl+CVhfln0XhZDdSVdN3HETYjvQrZplNQMatRKMMVcDdVuKx1kqSTLFwW++qlLGJ3XeKgSZpTDHApILs9KwRuTnNooCin5k76kNfLxaF3k7o6Zu0G/ddgXl9FyBFoj0g65LoksJcuA06MczmNh6uSxEvV2fStMDp0DxZsoGgT4fF/XlRKhj/YNCSWeuW5FAOAUtPapZljvaxYES+ZJBnpsuyFHuKXFTN2t6OOgTi+KjXHYKGBuG+0RuxLImIs42+Iew0QT6JdI8EqlQJCQ6mQtb0MOuozWXA2ukBcbNP/M5Wh+XZIZPkKR+Hrgr/FTS4TOxAwGW5B0nExiMe54Bqgr6HqgJ6TuxYiBuUhSgA7pVuyRfJcderpO9ZsSiDl0PIL6Cdg0ZKfrYgTrs+63CjdEhX0KyqUG51Y0LpDaF6Pp/nX5pp40briDUJSlimUVM+9IAxFUvUE8XMsCswYUl7hDOSYMxltsb9YgwpxIKGgT+7PDxVxyfQpdomlio3FVY6N9dxyVy5/7sE3pQCo8+eKf7fMp6RnRNmWBvo/AlOAx33Odhlp756LdY+PC1CeZ/Aq2B7nNhoI5MPFhzPBhpU60ECzcTdiz4q/WqbiM//Ug=
  - secure: DWr1spGbRgymOhvfDayETqdK5zEPfCNdUfFhUWVE/l/7OBhPbvq2c7c8nudk4d4D1+cpfOXQziYMJYWxaZfkUssZ6YF7BO4QmPsoupiA9to+Yl/zp9aUhQhS378Z3ReWs1LZUwN8mqsN08VS+TjoYzz4YTKqPILZ3VbYfz62Qm4VMVb82AQpUIc5L92TveqY4CmKttrPBOeLQyIy7Ce+imzPadIDX894PKCiCHUw9HZur/COOc7wwwOhgMr0MHn+h6XDPGbNEeadIzWG7o9LSuJe+F6pA1x9TZrlz3l74Lk46jN2jDAJoU6vB/12DCaz3ZYaIK4WtOn6H78YUbnOkzF+UXfHe/z8Z59womSBTnL2/zBZv3kEp2N3kQgptuqJlP2jaO6GH6ex6+bK6BHSi5VmZ6Xg8ee6cie0CjfSZ2qLtaDlh8E0doKbN9sqpEODjDWuz7OL1PC0M8lipx7iJbpIj/uvn+cRFYgkqaeTzG3HnpwM2pd/qPAbddZHdJHzXnrSkBULJWTLpQz1bE5lISpdgTReJBovet0liB9MHAjyOlQhyB1oC2BNB1SWLnUSb5L2tMq4i7wu3YmD3EAm8c8u3PQmffDOd98/7Zm+kGUf6NchEN3GEVFR1r475MilVagGeYv+FHk2E/nMVai02kUau1qZ2ck8/B515VMI7+k=
  - secure: jG9n3fg2eXUml8uCItwlN2hliThxZH9DWKcChZv77oR0G36b2+Tvs5k9AylQUSyb9mPQ4ccwrqxkqi/+6LZB6PJ0h5SbrmOv/DaDDotQrAgNMQJeY28fcKCF280m5MKJ69Onq9g5grzdrG2SeB6OyUQN9emmAS7bvE2bycm9D55llYi3/7TitKdgpdpzqO3kYU5UXvbmDM6ZxrHSeszuOadb5cgzX+wGFAoM0GCUcsf4AXjumFEeyNWwBQbcAjh3kXQlBuJN+SMKmIWkoe3HZ+6wI3LGirTDhkya1mqK/51X5zqdX7bg1wI1z3ViIA3N+rgMI34QDf4n33cKNc6/brKJx+r5oQh31cWn3NVDnFPd3gFsjwZsXNAGqNFWrgDOZ31a95AwVW9y/7MQAymDcNKqcLlLr5OxCYebmehAyJMB+BzICiAxgMad+jNxkwRGNrg6FFzm+r4PRtunth+jtmhidMTw2j4qVxMs8oXt9gWfSEZXMC923yhwtsCFOMVdZvDHWQ0x7TC1Fo47NeS6fQKXehtjRwr3P0lRQ/vGsvnjKYLU3SSiAM1VoJe2prmDM02nCenmmZqWAVyPXdMfOMMJ4bF6hAd1g/Wph5OPnzL1aY1Uei+y9s1h6quOW75VE73Kckm+hvXjfUQIQ+MGFiYLrVmy8vLUOjTzoSZePkc=
  - secure: rdYtT2roXd8jMniU3XLrDXmgpMGUdVXypZh6vUQiJrel2sN9bg0Uixn8zLsCBvHrXpRBzbeDis65hlfDGR8ZKl6eGlOFrneFTiX1iqf1piKwCAjBSgLmr9lKUzVQCZbtflnSVqLVb/r9hlV2oZaBLkuk7Z7JQy4CvivhI4isleSj/h8CJ9pynh1Gn5qXTab4tuDcsQFWtLYeX/ho2hXGk/qAdo4wz38lRPxoCLX6V9TwRLTs+pBgO+4bjfb64Tt0wloWzGCZsQgRcHP/hzaKOFi261rX17tmxvoUyoz/gtGQWxo/6v/YqCcf5rCPVeyiy9yXYmhslcWuDYt4H09XgnuEHBl0fQeortGcORC3jcLYYXDZZj3Iav2ou0OqgtceyEpFAyP0U41KKJpmvN+UZr5Z8oVYMj8LbKfPe1mUjsqeluKuo1O9Qq3BmgckeHQrkUrDAzMtfw8F4K3Ay/Ar6v7ONQceR5DcjGH6e8G5kFSWRKcM5KGK9XBZj582oME8+0N5bIpd+WHm5hB86baIDhT99kiAc8fa3S3qB9q6aj7NXLq5spmyoSyFD3hDSE+wcqxLToVd2/rXUQWSZcvogrSFUIYG6UlxQ5sAlT7T5YM4c2P0n1YLlKvdvPbIkksZ9dkMFWKPx1NblUsDs5ZMzGgjAXAXXy9uT9maI5WHpxI=
  - secure: rRrNO39kCh6Gt2alnmkRcLsBj3dXZczw6BSNMwSyCxnux0U2g9ErXvrPnlymGmdwmL4ExfXDirZv/zaTzBxbvk4LsVOk9jtfS539bjEJ+yxMoByzmoxAJobZAmxFutahH2ErB0DJ2YuP9WuD1HSrs4A0KDz4ntdgVPiPQH4CIecab26X6sa/b9lbEVyqSu0LlsBdO6vIcDNyeQhoEbL/pVJgazN+QFGQ14B5n4YJ7HZZ+rT9FChLnyuN9hUVaF+3+Azb3XV4KtHTX6xZUKky0cthpmp9DPQy0i5Usu0kfZBF8B5OoH+kYxVGcovZwH8VyC0mmozJoTD6qVjWdpgfHSC9QkKtihnQ4WAcOhTOo4DoGXncAD9g6p2BQXrKK27IN9cpzx7GhHCXhKWEqv6LU8/jFmx/z44UsWl5dV86i0IKrhyPqkTjm5f//HKNCbVdCrM6BGATdUdWBMF2Hn07yYHN3kdJIJX+8x/qZLvg9aIypo7zqfVrBP6CAXMHssn02cgOIjPT9Om6TQAXD1LV7l7yU5Zda4a9ze/4CwcRMZgY6kcnvcu51VrqDG0G8EDnJx97MrRphew+75Tvq8GSwjk/um5KTwLMh8dHoTw3EgFRGXGZkXZzIcuYOILAmF7Ctb5gdRbpYaXey0Mg5UIVbnS4LSUkpkaIB40KjH/e2mw=
  - secure: PiKwZ1r45k85cmik0kGxBUV2VCkSQ4fRQW7mJ1Fg1Q+sgzXEI0Vt8ahPiB+bE3G1XVWEuQBx98fwT964NOyOJe6P05zxMac3wWGaWx9WykkejZNdmn9otjT4mS737h9QEHcRrqhe7hF8rR2yqSCQSyzQ5khdSjC0cAADI8bxoDB3OyCrslvgIW0h+k61V8VppHpvh81d3ZzRtNzfS75IWr96pe1xnT+8G75nk/AaXAKd2bTq/axlBUlQojvjyj1CtvEwQKYw08mcaWazmLMpoMDt3Obt0zDzl8foZVeu0D58WriI43I0S4de6zOe5lnsyv/qPYlpBAZrKZttVUxEodZuIMCTSqhST3R6Vst9K19ZGglrx6ofyeJSxppFeP48wXcT/FvewuN4KNXD/YI9uISMKrTKSw/DudF4o8TnFtiPcpXQsHUC2/jzBuljnvUlB5u172CHpD8okhEzVZjbIEQXLHtc6MMSi4HsoVjL4UMPZuM3BJMwUPHK3+YdssFX6IpberQyEM19JTZoC79hOP3W9gyod0oiM1cv9af7Vt41tSNS/3r1pWd5RxTkRjZqY9ioQTw6Xv4lIY8pdnilKgiC7cHx593+QV4msormeiA2vZD/0UGTMFZHMp5j9lG3IoTwjLVMqSUkFnWJHCQFgISsnUSvp1ySmVFWHss9ez8=
