dist: trusty
language: java
sudo: required
jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
- oraclejdk8
- oraclejdk9
before_script:
- wget "https://github.com/nats-io/nats-server/releases/download/$nats_server_version/nats-server-$nats_server_version-linux-amd64.zip"
  -O tmp.zip
- unzip tmp.zip
- mv nats-server-$nats_server_version-linux-amd64 nats-server
before_install:
- openssl aes-256-cbc -K $encrypted_f07928735f08_key -iv $encrypted_f07928735f08_iv
  -in .travis/nats.travis.gpg.enc -out .travis/nats.travis.gpg -d
install:
- "./gradlew assemble -x signArchives"
script:
- "./gradlew check"
#for testing - "./gradlew build -x test"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew test jacocoTestReport coveralls"
- |
  if [ "${TRAVIS_BRANCH}" == "travis_deploy" ] && [ -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_JDK_VERSION}" == "oraclejdk8" ]; then
    ./gradlew -i sign publishToSonatype
  fi
- |
  if [ "${TRAVIS_BRANCH}" == "master" ] && [ -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_JDK_VERSION}" == "oraclejdk8" ]; then
    ./gradlew -i sign publishToSonatype
  fi
- |
  if [ "${TRAVIS_BRANCH}" == "master" ] && [ ! -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_JDK_VERSION}" == "oraclejdk8" ]; then
    ./gradlew -i sign publishToSonatype closeAndReleaseRepository
  fi

env:
  global:
  - nats_server_version=v2.0.4
  - nats_server_path=$TRAVIS_BUILD_DIR/nats-server/nats-server
  - GPG_KEYRING_FILE=.travis/nats.travis.gpg
  - secure: yvOfk7kJzzTQ38n444jTDets24FZmxewwb3lrhXwpHTwOnQyq/B8QaHeqvhneECMc0Bq5M4blTlJ/wOWJAvs61POv2QVkyw+u8cVNROzkb8GPaH4ybPo8HMl33EHFNqh1KRo2C9hAPMYbbTjKCVY2UdkdfJ2l4lN/Awk7uEDX8ckc/sENhDeQjY/xoGZUP28O568Eg4ZxN3fr3WEV/0T+R15YyL2X0ev8MiGJM5TojXnNFKdb5fkUodRWwiY8JDn5xzP7xUzzen7MqE/5YNTcIC6haU8LToJM2gXEQtdoWLZqMPWr7k4A+eTBO5vl9qWrPBaOodFJYKzEjrEDfHj5RR9uaufEsnwQzXKw1ODrIFVZiC2n73j/tatWDI+vjnJ5tO+VMwWj53qdBYrvYeyewIT3cz9rrDHH8fGINsKAsk6HgWM3SMgeNSuXjRN0ePxEph5FVQ3ZUjF1ZXp90O7kjD5kXg/jVs6GrhCviRT3fx6Z4hyat9ytshy66jqcttHEfJ5sSOBg8fVbWJjLbxmghWUFp1fuc0HGNiMJStEyOBai5AkG6uJccTlgjlNL/8mgEF+fxo8HGVyStQzRnr7LJuCmWW9hx/aBVmqXR4p6cRgsSO09PvHRmcsLQoktCxVxsvcfblQqMbiQKjsJ4tXLe0U88DMOHnEGOgtik/tt+4=
  - secure: isW18c01AJEDAPUUl6rKcewHxOqItTW0TiiEIrWQqQP/C3O06WgAbiFYVFPJ9zCi6me0Wj3YMmEoxiYBhFdgH/O5xoQnnU7xIfD9hcmByglsoyGsK/Wz0wcERoVf9bfbVQkj9q/Mg7kaUZCMWqcFR3CqHEGu8UH5x7ecDW5FXfAQDjN5czT1j1VAwhHZCfIktJuy/GzoFGgRJpvnFPSlHmi0I8fApoX43tmOCkTVHnaXt9CDL3A5EIKtok5dwu0FF5d9hQFncJB8gqGxd+r8a3W3+0Gfgdou3x+AlGTf3R62LgB03GY0MFrMVfanWJE1ORdV0o9hC3AiwOsKBTungZ0arQeXtDXHSeMY52O6u7C8MCwQgbTmzO2YsmMwwTL98PPQxEJ6c8r7WBAfxzxxRTJ/QjPqQdyWV9dFWOnsmEhBLM2Wi858dJlw5fDEoHgy8EUZTQcquUWqEzTJca1VdrLza/PlND8dqfAjxqINtpsXu88JsLUu5VjFiLwln5NpdNKfcY4oaPiLLYdrSgdxBfHCCISP+r8iqgKLDguFwza3xcPSFwqtEq8aYmy0fjgd0c9hlz6oe0NvLc4kPJf4q9NDjffUXBciiv8VXdL3YyRG67h9AF+ndbM8NHsup5FfmALfq2bGIpe4USIqoOAZFUSa35hPDW87C7Z4vvPvb9I=
  - secure: YdGX/qrEsHAdRmp0+pp2HWmcs6hfG58FWfmHZqb9ZBQHTn0AgiGWia+McQeULpq3fe8NDT+W2DWaRgwWRup3yp9bnlvP+1PmPzo0mZhoHIYvGrcc5RCiA5yv9gBPyX6Xhbi9LaXGsUjm4aInDmHihDV5GxhgJa1+2q8/KOdm9ck1bNkdG2EVx//JDlMzOKrAlVwpK4Hpi3XSK6V70YUiPYK7h/8cJztjJd/rNFz9iYj0qDh8t1VAMOmqWL/otY1jBzDxGAdN30yXnEJwjtsDwSLvaSWp3g/s4mpBF237D5L53Y71wcadkRi69LB0ZR4mqHkEUOA/EHOIBTubf+tKavbU9UPu+3QDRj1ohCklrh8/eaAWXR4ntyTcL+TmP48lQeZA0O+IwglxrCTvRB/lhX5sUUVCIMejaMCiPlzXMcGzJZixl1ZVgEALq77UVv+d+xnC8oFmfdkAFsF8jbcMwqe0D3+uRHqlR3wZXPTMyb/NxysYfvNBD8xVU6vPqLWW7KPxDtEpCO4m2J6Tn1KxuAocowcPUiL/Xdi5Yc5PV5k10kHjBELhAAexw+1doyzlKKwZdjLZt/4KeDxYETPKFgkUrnk7HUCoMdlopIhBMxm5j0fABBk9cnX8DZ826ZlgIJ5YFgkZJkPLyZv8RALTsTzeiyRroPvDckF7+wELkCY=
  - secure: n1r8PLtKgQbW0v0C+MzKRg+EcSXsBBnBe1u8/OyPdC84X6Zwe7JRv/C55Zx71I3yzLhlY6zjBtsNBTO1hgViDPlnDGFl3BL2+fQEi6sofqThgaTSB4UIqTVY8jDYvXp7fcLqN4jM83ElTlfWRSlQHyQ5FKLdla81EcGOB+cL/BObE+Adf9CGGcf7oUd+2MVU+mrEZZTRvaUk32eXzYqEHfib1EHOvyf4ACXbGHe7bIaO6dxAhVNlTjbDdyEdSDFTrtNCFA+t0780IcPhf7uaOy/JBFZ2uL33IqUGih44/GsHj2zJjJmHEL2NtcBhLeuAbRFT6VuE+13DtaB7eNwuXCD4d553vFWK0jT3eKmVgePswHmB1Vs8wsGa92LQLP8vHDCqeMBYzCxWK3hlJj+bzok9AXdyn0IECMTMXc9KLNDIfHrvvmu1DfpuKklmTETII4zSkcPkMAO+VU+kxJ+krf7CYb519KDGpF97bLBWnBboBj3WOx70ux1Fm9ah28YEMPuGHp3Ft6o7ozi2eP8a4YxXo8wQUxe62UIx0e4hDv43aa2Qzvnu9ldEL21WduzlBGjjPTD2GxtkIaB8H1nmH9sgShGVfNwcba3LlO/xU5nUTbrQVcP6WEvlvkdfQmbX4AGh1jCWLWVvxjyPxfZrlARE1JRV5x0oOeH79KA9a18=
