name: Build a Branch Specific Snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      BRANCH_REF_NAME: ${{ github.ref_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14' # Quotes required to prevent YAML converting to number
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Nats Server
        run: |
          pkill -9 nats-server 2>/dev/null || true
          mkdir -p ~/.local/bin
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go build -o ~/.local/bin/nats-server
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: chmod +x gradlew && ./gradlew clean compileJava
      - name: Verify Javadoc
        if: ${{ success() }}
        run: ./gradlew javadoc
      - name: Publish Branch Snapshot
        if: ${{ success() }}
        run: ./gradlew -i publishToSonatype
      - name: Clean up
        if: always()
        run: pkill -9 nats-server 2>/dev/null || true
