name: Build a Branch Specific Snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      BRANCH_SNAPSHOT: ${{ github.ref_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GODEBUG: x509sha1=1
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.9'
      - name: Install Nats Server
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          git checkout tags/v2.9.18 -b nscustom
          go get
          go build main.go
          mkdir -p ~/.local/bin
          cp main ~/.local/bin/nats-server
          cd ..
          rm -rf nats-server
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test jacocoTestReport coveralls
      - name: Verify Javadoc
        if: ${{ success() }}
        run: ./gradlew javadoc
      - name: Publish Branch Snapshot
        if: ${{ success() }}
        run: ./gradlew -i publishToSonatype


