name: Build Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GODEBUG: x509sha1=1
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
      - name: Install Nats Server
        run: |
          pkill -9 nats-server 2>/dev/null || true
          mkdir -p ~/.local/bin
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          git checkout tags/v2.11.8 -b release
          go build -o ~/.local/bin/nats-server
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test jacocoTestReport coveralls
      - name: Verify Javadoc
        run: ./gradlew javadoc
      - name: Clean up
        if: always()
        run: pkill -9 nats-server 2>/dev/null || true
